import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProductProvider } from "./context/ProductContext";
import Navbar from "./component/Navbar";
export const metadata = {
  title: "Nextjs ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className="bg-black text-light"
      >
        <ProductProvider>
          <Navbar/>
           {children}
        </ProductProvider>
        
      </body>
    </html>
  );
}
